version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (encoding/json.Encoder).Encode
        - (os/exec.Cmd).Run
        - os.Remove
        - (io.Closer).Close
        - (*os.File).Close
        - (net/http.Response.Body).Close
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
